version: '3.8'

services:
  discord-music-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge